[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vir-tui"
version = "2.3.0"
description = "A lightweight, terminal UI primitive library for the VirInvictus CLI toolchain."
readme = "README.md"
requires-python = ">=3.14"
authors = [
    { name = "Brandon LaRocque" }
]
dependencies = []

[tool.ruff]
lint.extend-ignore = ['F401', 'BLE001', 'S110', 'RUF059', 'I001']
